
services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pswd@12345
    ports:
      - "127.0.0.1:4321:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlvolume: